// ══════════════════════════════════════════════════════════════════════
// script-templates.ts — Python reproduction script generator
// ══════════════════════════════════════════════════════════════════════

export interface ScriptContext {
  experimentId: string;
  modelType: string;
  hyperparameters: Record<string, unknown>;
  cvMean: number;
  trainMean: number;
  artifactPath: string;
  metricName: string;
  features: string[];
  workspacePath: string;
}

const MODEL_IMPORTS: Record<string, string> = {
  xgboost: "from xgboost import XGBRegressor, XGBClassifier",
  lightgbm: "from lightgbm import LGBMRegressor, LGBMClassifier",
  catboost: "from catboost import CatBoostRegressor, CatBoostClassifier",
  ridge: "from sklearn.linear_model import Ridge",
  lasso: "from sklearn.linear_model import Lasso",
  elasticnet: "from sklearn.linear_model import ElasticNet",
  randomforest: "from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier",
  gradientboosting: "from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier",
  mlp: "from sklearn.neural_network import MLPRegressor, MLPClassifier",
  svm: "from sklearn.svm import SVR, SVC",
};

function resolveModelImport(modelType: string): string {
  const key = modelType.toLowerCase().replace(/[^a-z]/g, "");
  for (const [k, v] of Object.entries(MODEL_IMPORTS)) {
    if (key.includes(k)) return v;
  }
  return `# TODO: add import for "${modelType}"`;
}

function resolveModelClass(modelType: string): string {
  const key = modelType.toLowerCase().replace(/[^a-z]/g, "");
  if (key.includes("xgboost") || key.includes("xgb")) return "XGBRegressor";
  if (key.includes("lightgbm") || key.includes("lgbm")) return "LGBMRegressor";
  if (key.includes("catboost")) return "CatBoostRegressor";
  if (key.includes("ridge")) return "Ridge";
  if (key.includes("lasso")) return "Lasso";
  if (key.includes("elasticnet")) return "ElasticNet";
  if (key.includes("randomforest")) return "RandomForestRegressor";
  if (key.includes("gradientboosting")) return "GradientBoostingRegressor";
  if (key.includes("mlp")) return "MLPRegressor";
  if (key.includes("svm")) return "SVR";
  return "model_class";
}

export function generateReproductionScript(ctx: ScriptContext): string {
  const hpJson = JSON.stringify(ctx.hyperparameters, null, 2);
  const featuresJson = JSON.stringify(ctx.features, null, 2);
  const modelImport = resolveModelImport(ctx.modelType);
  const modelClass = resolveModelClass(ctx.modelType);

  return `"""
Reproduction script for ${ctx.modelType} (Experiment #${ctx.experimentId})
Generated by Formiga ML Pipeline

Original metrics:
  CV Mean (${ctx.metricName}): ${ctx.cvMean.toFixed(6)}
  Train Mean: ${ctx.trainMean.toFixed(6)}
"""

import pandas as pd
import pickle
import json
import numpy as np
from pathlib import Path
from sklearn.model_selection import cross_val_score
${modelImport}

# ── Configuration ─────────────────────────────────────────────────────
WORKSPACE = Path("${ctx.workspacePath}")
MODEL_ARTIFACT = WORKSPACE / "${ctx.artifactPath}"
FEATURES_PATH = WORKSPACE / "artifacts" / "features.parquet"
SPLIT_PATH = WORKSPACE / "artifacts" / "split.pkl"

HYPERPARAMETERS = ${hpJson}

FEATURES = ${featuresJson}

METRIC = "${ctx.metricName}"

# ── Load data ─────────────────────────────────────────────────────────
features_df = pd.read_parquet(FEATURES_PATH)

with open(SPLIT_PATH, "rb") as f:
    split = pickle.load(f)

train_idx = split["train_idx"] if "train_idx" in split else split.get("train", [])
val_idx = split["val_idx"] if "val_idx" in split else split.get("val", [])

target_col = [c for c in features_df.columns if c.startswith("target") or c == "y"]
if not target_col:
    target_col = [features_df.columns[-1]]

X = features_df[FEATURES] if FEATURES else features_df.drop(columns=target_col + ["__split"], errors="ignore")
y = features_df[target_col[0]]

X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
X_val, y_val = X.iloc[val_idx], y.iloc[val_idx]

# ── Option A: Load pre-trained model ──────────────────────────────────
if MODEL_ARTIFACT.exists():
    with open(MODEL_ARTIFACT, "rb") as f:
        model = pickle.load(f)
    print(f"Loaded model from {MODEL_ARTIFACT}")
else:
    print(f"Artifact not found at {MODEL_ARTIFACT}, training from scratch...")
    # ── Option B: Train from scratch ──────────────────────────────────
    model = ${modelClass}(**HYPERPARAMETERS)
    model.fit(X_train, y_train)

# ── Evaluate ──────────────────────────────────────────────────────────
from sklearn.metrics import mean_squared_error, r2_score

train_pred = model.predict(X_train)
val_pred = model.predict(X_val)

train_rmse = np.sqrt(mean_squared_error(y_train, train_pred))
val_rmse = np.sqrt(mean_squared_error(y_val, val_pred))
train_r2 = r2_score(y_train, train_pred)
val_r2 = r2_score(y_val, val_pred)

print(f"\\nResults:")
print(f"  Train RMSE: {train_rmse:.4f}")
print(f"  Val RMSE:   {val_rmse:.4f}")
print(f"  Train R²:   {train_r2:.4f}")
print(f"  Val R²:     {val_r2:.4f}")
print(f"\\nExpected CV Mean (${ctx.metricName}): ${ctx.cvMean.toFixed(6)}")
`;
}
